.venv/bin/torchrun --master_port 29502 --nproc_per_node=1 --nnodes=1 lbm2/main.py \
  --model "include lbm2/config_presets/models/fake_policy.yaml" \
  --data "include lbm2/config_presets/data/lbm_data_params.yaml" \
  --data.processor HuggingFaceTB/SmolVLM-256M-Instruct \
  --data.image_size 512 \
  --data.img_num_tokens 64 \
  --distributed.fsdp_pure_bf16 True \
  --distributed.use_distributed True \
  --model.resume_weights_only True \
  --num_checkpoints 3 \
  --hparams.per_gpu_batch_size 8 \
  --hparams.global_batch_size 8 \
  --hparams.grad_clip_norm 1.0 \
  --hparams.lr 5e-4 \
  --hparams.lr_cooldown_end 1e-5 \
  --remote_sync s3://tri-ml-datasets-uw2/lbm2/fake_policy/model_checkpoints/ \
  --data.seq_len 2048 \
  --total_train_samples 1000 \
  --data.allow_multiple_epochs True \
  --data.num_workers 30 \
  --wandb True
