.venv/bin/torchrun --master_port 29506 --nproc_per_node=2 --nnodes=1 vla_foundry/main.py \
  --model "include vla_foundry/config_presets/models/diffusion_policy.yaml" \
  --model.clip.freeze_text_encoder True \
  --model.transformer.is_causal True \
  --model.noise_scheduler.num_timesteps 100 \
  --model.disable_text True \
  --data "include vla_foundry/config_presets/data/mmt_data_params.yaml" \
  --data.dataset_manifest ["s3://tri-mmt-data/richard/diffusion_policy/robosuite/cube/lift_right_discrete_with_cube_state_0-8_uniform_noise_processed/lift_right_discrete_with_cube_state_0-8_uniform_noise_800/shards/manifest.jsonl"] \
  --data.dataset_statistics ["s3://tri-mmt-data/richard/diffusion_policy/robosuite/cube/lift_right_discrete_with_cube_state_0-8_uniform_noise_processed/lift_right_discrete_with_cube_state_0-8_uniform_noise_800/shards/stats.json"] \
  --data.dataset_weighting [1.0] \
  --data.dataset_modality ["robotics"] \
  --data.dataset_weighting [1.0] \
  --data.image_size 224 \
  --data.action_dim 7 \
  --data.processor openai/clip-vit-base-patch16 \
  --data.img_num_tokens 50 \
  --data.allow_multiple_epochs True \
  --data.num_workers 4 \
  --data.seq_len 2048 \
  --data.lowdim_past_timesteps 0 \
  --data.lowdim_future_timesteps 4 \
  --distributed.fsdp False \
  --num_checkpoints 3 \
  --hparams.precision amp_bf16 \
  --hparams.loss_function mse \
  --hparams.per_gpu_batch_size 32 \
  --hparams.global_batch_size 64 \
  --hparams.grad_clip_norm 1.0 \
  --hparams.lr 3e-4 \
  --hparams.lr_cooldown_end 1e-5 \
  --remote_sync s3://tri-mmt-data/richard/diffusion_policy/robosuite/cube/model_checkpoints/lift_right_discrete_with_cube_state_0-8_uniform_noise_800_patch16 \
  --total_train_samples 10000000 \
  --wandb True \
  --wandb_project_name diffusion-policy-mmt-cube \
  --data.normalization.enabled False \
