.venv/bin/torchrun --nproc_per_node=8 --nnodes=1 vla_foundry/main.py \
--model "include vla_foundry/config_presets/models/vlm_3b.yaml" \
--model.vit.type vit_hf \
--model.vit.hf_pretrained vit_base_patch16_siglip_224 \
--distributed.fsdp True \
--data.type image_caption \
--data.processor google/paligemma-3b-pt-224 \
--data.dataset_manifest ["s3://tri-ml-datasets/datasets/datacompdr_1b/manifest.jsonl"] \
--data.dataset_modality ["image_caption"] \
--data.dataset_weighting [1.0] \
--data.img_num_tokens 196 \
--data.seq_len 2048 \
--total_train_samples 14_000_000 \
--num_checkpoints 5 \
--hparams.per_gpu_batch_size 2 \
--hparams.global_batch_size 64 \
--model.vit.hidden_dim 768 \
--model.vit.projector_pixel_shuffle_factor 1 \
--remote_sync s3://tri-ml-datasets/vla_foundry_scratch/models/vlm_siglip_paligemma_3b \
--wandb True \
"$@"