#    --camera_names "include lbm2/config_presets/data/lbm_data_camera_names.yaml" \
uv run --group preprocessing python lbm2/data/preprocessing/preprocess_lbm_data.py \
    --source_episodes "['s3://robotics-manip-lbm/efs/data/tasks/PickAndPlaceBox/cabot/sim/bc/teleop/2025-02-11T17-04-00-05-00/']" \
    --output_dir s3://sagemaker-us-west-2-124224456861/vlm_datasets/preprocess_sample/lbm/PickAndPlaceBox/cabot/sim/ \
    --past_lowdim_steps 1 \
    --future_lowdim_steps 14 \
    --image_indices "[-1, 0]" \
    --stride 1 \
    --max_padding_left 3 \
    --max_padding_right 15 \
    --padding_strategy zero \
    --filter_still_samples False \
    --still_threshold 0.05 \
    --camera_discard_keys "include lbm2/config_presets/data/lbm_data_discard_key.yaml" \
    --camera_names "include lbm2/config_presets/data/lbm_data_camera_names.yaml" \
    --samples_per_shard 100 \
    --jpeg_quality 95 \
    --num_workers 40 \
    --max_episodes_to_process -1 \
    --fail_on_nan True \
    --shuffle_buffer_size 10000 \
    --shuffle_input_files True \
    --enable_incremental_updates True \
    --update_frequency 10 \
    --skip_git_tagging False \
    --resize_images_size "[256, 342]" \
    --use_gpu_resize True \
    --resume False
