# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GetPolicyMetadata.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, "", "GetPolicyMetadata.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17GetPolicyMetadata.proto\x12\x14lbm_policy_interface"\xc0\x02\n\x0ePolicyMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nskill_type\x18\x02 \x01(\t\x12\x17\n\x0f\x63heckpoint_path\x18\x03 \x01(\t\x12\x10\n\x08git_repo\x18\x04 \x01(\t\x12\x0f\n\x07git_sha\x18\x05 \x01(\t\x12\x19\n\x11raw_policy_config\x18\x06 \x01(\t\x12\x1f\n\x17is_language_conditioned\x18\x07 \x01(\x08\x12Y\n\x13runtime_information\x18\x08 \x03(\x0b\x32<.lbm_policy_interface.PolicyMetadata.RuntimeInformationEntry\x1a\x39\n\x17RuntimeInformationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"5\n\x18GetPolicyMetadataRequest\x12\x19\n\x11\x63lient_identifier\x18\x01 \x01(\t"k\n\x19GetPolicyMetadataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12=\n\x0fpolicy_metadata\x18\x02 \x01(\x0b\x32$.lbm_policy_interface.PolicyMetadata2\x90\x01\n\x18GetPolicyMetadataService\x12t\n\x11GetPolicyMetadata\x12..lbm_policy_interface.GetPolicyMetadataRequest\x1a/.lbm_policy_interface.GetPolicyMetadataResponseb\x06proto3'  # noqa: E501
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "GetPolicyMetadata_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_POLICYMETADATA_RUNTIMEINFORMATIONENTRY"]._loaded_options = None
    _globals["_POLICYMETADATA_RUNTIMEINFORMATIONENTRY"]._serialized_options = b"8\001"
    _globals["_POLICYMETADATA"]._serialized_start = 50
    _globals["_POLICYMETADATA"]._serialized_end = 370
    _globals["_POLICYMETADATA_RUNTIMEINFORMATIONENTRY"]._serialized_start = 313
    _globals["_POLICYMETADATA_RUNTIMEINFORMATIONENTRY"]._serialized_end = 370
    _globals["_GETPOLICYMETADATAREQUEST"]._serialized_start = 372
    _globals["_GETPOLICYMETADATAREQUEST"]._serialized_end = 425
    _globals["_GETPOLICYMETADATARESPONSE"]._serialized_start = 427
    _globals["_GETPOLICYMETADATARESPONSE"]._serialized_end = 534
    _globals["_GETPOLICYMETADATASERVICE"]._serialized_start = 537
    _globals["_GETPOLICYMETADATASERVICE"]._serialized_end = 681
# @@protoc_insertion_point(module_scope)
