# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PolicyReset.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, "", "PolicyReset.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11PolicyReset.proto\x12\x14lbm_policy_interface"=\n\x12PolicyResetRequest\x12\x19\n\x11\x63lient_identifier\x18\x01 \x01(\t\x12\x0c\n\x04seed\x18\x02 \x01(\r"&\n\x13PolicyResetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32x\n\x12PolicyResetService\x12\x62\n\x0bPolicyReset\x12(.lbm_policy_interface.PolicyResetRequest\x1a).lbm_policy_interface.PolicyResetResponseb\x06proto3'  # noqa: E501
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "PolicyReset_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_POLICYRESETREQUEST"]._serialized_start = 43
    _globals["_POLICYRESETREQUEST"]._serialized_end = 104
    _globals["_POLICYRESETRESPONSE"]._serialized_start = 106
    _globals["_POLICYRESETRESPONSE"]._serialized_end = 144
    _globals["_POLICYRESETSERVICE"]._serialized_start = 146
    _globals["_POLICYRESETSERVICE"]._serialized_end = 266
# @@protoc_insertion_point(module_scope)
