# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
from grpc_workspace.proto import PolicyReset_pb2 as PolicyReset__pb2

GRPC_GENERATED_VERSION = "1.71.2"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in PolicyReset_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class PolicyResetServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PolicyReset = channel.unary_unary(
            "/lbm_policy_interface.PolicyResetService/PolicyReset",
            request_serializer=PolicyReset__pb2.PolicyResetRequest.SerializeToString,
            response_deserializer=PolicyReset__pb2.PolicyResetResponse.FromString,
            _registered_method=True,
        )


class PolicyResetServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PolicyReset(self, request, context):
        """gRPC service definition for gym-API communication between policy and
        environment. Identical functionality to the ROS PolicyReset service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PolicyResetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "PolicyReset": grpc.unary_unary_rpc_method_handler(
            servicer.PolicyReset,
            request_deserializer=PolicyReset__pb2.PolicyResetRequest.FromString,
            response_serializer=PolicyReset__pb2.PolicyResetResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "lbm_policy_interface.PolicyResetService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("lbm_policy_interface.PolicyResetService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class PolicyResetService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PolicyReset(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/lbm_policy_interface.PolicyResetService/PolicyReset",
            PolicyReset__pb2.PolicyResetRequest.SerializeToString,
            PolicyReset__pb2.PolicyResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
