source .venv/bin/activate && python lbm2/data/scripts/preprocessing/preprocess_lbm_to_tar.py \
    --source_episodes "['s3://robotics-manip-lbm/efs/data/tasks/PickAndPlaceBox/cabot/sim/bc/teleop/2025-02-11T17-04-00-05-00/']" \
    --output_dir s3://tri-ml-datasets-uw2/preprocess_lbm_test/lbm/PickAndPlaceBox/cabot/sim/ \
    --language_annotations_path lbm2/data/scripts/preprocessing/lbm_language_annotations.yaml \
    --camera_discard_keys "include lbm2/config_presets/data/lbm_data_discard_key.yaml" \
    --camera_names "include lbm2/config_presets/data/lbm_data_camera_names.yaml" \
    --past_lowdim_steps 1 \
    --future_lowdim_steps 14 \
    --image_indices "[-1, 0]" \
    --stride 1 \
    --max_padding_left 3 \
    --max_padding_right 12 \
    --samples_per_shard 5 \
    --max_episodes_to_process 1 \
    --jpeg_quality 5 \
    --filter_still_samples False \
    --compute_statistics True \
    --still_threshold 0.05 \
    --resize_images_size "[224, 224]"