source .venv/bin/activate && python vla_foundry/data/scripts/preprocessing/preprocess_lbm_to_tar.py \
    --source_episodes "['s3://robotics-manip-lbm/efs/data/tasks/PickAndPlaceBox/cabot/sim/bc/teleop/2025-02-11T17-04-00-05-00/',]" \
    --output_dir s3://tri-ml-datasets-uw2/vlm_datasets/preprocess_512_shuffle/lbm/PickAndPlaceBox/cabot/sim/ \
    --past_lowdim_steps 1 \
    --future_lowdim_steps 14 \
    --image_indices "[-1, 0]" \
    --stride 1 \
    --max_padding_left 3 \
    --max_padding_right 15 \
    --padding_strategy copy \
    --filter_still_samples False \
    --still_threshold 0.05 \
    --camera_discard_keys "include vla_foundry/config_presets/data/lbm_data_discard_key.yaml" \
    --camera_names "include vla_foundry/config_presets/data/lbm_data_camera_names.yaml" \
    --samples_per_shard 100 \
    --jpeg_quality 95 \
    --max_episodes_to_process -1 \
    --fail_on_nan True \
    --skip_git_tagging False \
    --resize_images_size "[224, 224]"