name: GitHub Issues to Asana Tasks

on:
  issues:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]

jobs:
  issues-to-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Issues To Asana Tasks
        uses: ideasonpurpose/github-issues-asana-tasks-action@v0.0.24
        env:
          ASANA_PAT: ${{ secrets.ASANA_PAT }}
